pbs_job_queue: "batch"
server_path: '/home/valder'
upload_path: '/home/valder/data/vtrans/upload'
trans_path: '/home/valder/data/vtrans/transcode'
allow_extension: "mp4;3gp;flv;mpg"
fileDesc: "File(*.mp4;*.3pg;*.mpg*;*.flv)"
max_file_size: 512MB
trans_cmd: "/opt/ffmpeg/bin/ffmpeg"

#$download_video_info_path=File.join(Rails.root, "log", "download")
#$transcode_video_info_path=File.join(Rails.root, "log", "transcode")
#$default_pbs_path=File.join(Rails.root, "log", "torque")


